apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumberjack-rel-1-0-0
  namespace: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumberjack
  template:
    metadata:
      name: lumberjack-rel-1-0-0
      labels:
        app: lumberjack
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: lumberjack-rel-1-0-0
          image: example.io/lumberjack:1.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
